### ISSUE TITLE
move this over to dyne organization for collective maintenance?

### ISSUE THREAD

**Issue by jaromil** [gregtzar/docker-tomb#1]
Hi Greg! with a new version of Tomb I've linked your project here and included you in the credit history :^) its awesome to have Tomb running on more operating systems this way.

I'm also testing it locally on WSL and would like to eventually contribute some things like tomb signature checks and perhaps a port to Alpine.

Would you be OK to move this repo inside tomb/extras ? you'd maintain access of course and it would allow contributions from more people already involved in Tomb.

Let me know, cheers!

**Comment by gregtzar** [comment]
@jaromil Sorry about the delay on this response. I'm fine with moving this into the tomb repo (if you haven't already). Do you need anything from me to do it?

**Comment by jaromil** [comment]
No needs, yes I've done already :^) thanks again. BTW the current show-stopper on WSL2 is the lack of loop-mount.
